### ISSUE TITLE
Chances

### ISSUE THREAD

**Issue by ManiakMCPE** [davidgamingzz/MiningRewards#3]
Cannot change chances. Even when lowered below 100 it still gives the rewards 100% of the time.

**Comment by davidgamingzz** [comment]
The chances are for the chances of getting it while mining. You can change the chances of getting the reward in the crate that receives by adding a duplicate of the reward in the configuration file. If I did not answer your question, please specify what you mean.

**Comment by ManiakMCPE** [comment]
I changed the chance to 1 and I still get it every time I mine. Fix it.

**Comment by davidgamingzz** [comment]
> I changed the chance to 1 and I still get it every time I mine. Fix it.

Can you be more specific on what you're trying to accomplish, please?

**Comment by ManiakMCPE** [comment]
I. Changed. The. Percentage. To. 1. And. I. Still. Get. A. Reward. Every. Time. I. Mine. A. Block.

**Comment by davidgamingzz** [comment]
If you set the chance to 1, it will be 1 out of 1. If you set it to 1000, it will be 1 out of 1000.

**Comment by ManiakMCPE** [comment]
You should really clarify that. Many people will assume if it's default set to 100 that means it's 100%.

**Comment by davidgamingzz** [comment]
I’ll clarify that in my next update, which will be soon.
