### ISSUE TITLE
Rewards given in protected areas

### ISSUE THREAD

**Issue by 95CivicSi** [davidgamingzz/MiningRewards#9]
Whenever a player breaks blocks in protected areas, MiningReward still gives the player a reward even when area protection cancels the event.

**Comment by beaconcreaft** [comment]
Yups, same

**Comment by 95CivicSi** [comment]
PR #8 Fixes this issue and #5 

For anyone who wants to test it, you can download the updated plugin from Poggit here:

https://poggit.pmmp.io/r/57385/MiningRewards_pr-2.phar
